# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0002_auto_20170331_0753_squashed_0005_auto_20170331_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_isin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
