# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0003_asset_asset_isin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='am_type',
            field=models.CharField(choices=[('N', 'None'), ('U', 'Unsolicited'), ('D', 'Discretionary')], default='N', max_length=1, verbose_name='AM Type'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='am_type',
            field=models.CharField(choices=[('N', 'None'), ('U', 'Unsolicited'), ('D', 'Discretionary')], default='N', max_length=1, verbose_name='AM Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('M', 'Market'), ('L', 'Limit')], default='M', max_length=1, verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('M', 'Market'), ('L', 'Limit')], default='M', max_length=1, verbose_name='Execution'),
        ),
    ]
