# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0004_auto_20170620_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_qty_unit',
            field=models.CharField(default='shares', max_length=20, verbose_name='Qty unit'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_qty_unit',
            field=models.CharField(default='shares', max_length=20, verbose_name='Qty unit'),
        ),
    ]
