# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0004_auto_20170710_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_origin',
            field=models.CharField(default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_origin',
            field=models.CharField(default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='custodian',
            name='custodian_origin',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
