# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 08:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import zipline_app.models.zipline_app.side


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0005_auto_20170620_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='commission',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
