# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0005_auto_20170725_1150_squashed_0006_auto_20170725_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_qty_unit',
            new_name='order_unit',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_qty_unit',
            new_name='order_unit',
        ),
    ]
