# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('zipline_app', '0006_auto_20170801_1054'), ('zipline_app', '0007_auto_20170801_1126'), ('zipline_app', '0008_fill_fill_unit')]

    dependencies = [
        ('zipline_app', '0005_auto_20170725_1150_squashed_0006_auto_20170725_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_qty_unit',
            new_name='order_unit',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_qty_unit',
            new_name='order_unit',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Qty unit'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Qty unit'),
        ),
        migrations.AddField(
            model_name='fill',
            name='fill_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Unit'),
        ),
    ]
