# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0006_auto_20170801_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Qty unit'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Qty unit'),
        ),
    ]
