# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0006_auto_20170703_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='status',
            field=models.CharField(choices=[('P', 'Placed'), ('C', 'Completed')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
