# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 10:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import zipline_app.models.zipline_app.side


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0006_auto_20170801_1054_squashed_0008_fill_fill_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='fill_qty_unsigned',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty/Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_qty_unsigned',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty/Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_qty_unsigned',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty/Amount'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Unit'),
        ),
    ]
