# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zipline_app.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zipline_app', '0007_auto_20170801_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=zipline_app.utils.now_minute, verbose_name='Placement date')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
