# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0007_fill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='category',
            field=models.CharField(choices=[('P', 'Principal'), ('A', 'Agent')], default='P', max_length=1, verbose_name='Order Category'),
        ),
    ]
