# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0007_auto_20170801_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='fill_unit',
            field=models.CharField(choices=[('S', 'Share'), ('C', 'Currency')], default='S', max_length=1, verbose_name='Unit'),
        ),
    ]
