# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0008_fill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
