# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0008_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='fill_status',
        ),
    ]
