# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0009_fill_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='trade_date',
            field=models.DateField(default=datetime.date.today, verbose_name='trade date'),
        ),
    ]
