# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0009_remove_fill_fill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='dedicated_to_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zipline_app.Order', verbose_name='Order'),
        ),
    ]
