# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0010_fill_trade_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fill',
            old_name='status',
            new_name='fill_status',
        ),
    ]
