# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 03:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import zipline_app.models.zipline_app.side


class Migration(migrations.Migration):

    replaces = [('zipline_app', '0011_auto_20170803_1810'), ('zipline_app', '0012_auto_20170803_1938'), ('zipline_app', '0013_auto_20170804_0532')]

    dependencies = [
        ('zipline_app', '0010_auto_20170803_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_qty_unsigned',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty/Amount'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='commission',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='limit_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_qty_unsigned',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty/Amount'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_qty_unsigned',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty/Amount'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
    ]
