# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0011_auto_20170704_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='votes',
        ),
    ]
