# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0013_auto_20170815_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Account', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Account', verbose_name='Client'),
        ),
    ]
