# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0015_auto_20170817_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_status',
        ),
    ]
