# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 02:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import zipline_app.models.zipline_app.side


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0016_auto_20170817_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='commission',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
