# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 15:07
from __future__ import unicode_literals

from django.db import migrations


def set_is_confirmed(apps, schema_editor):
    Order = apps.get_model('zipline_app', 'Order')
    Order.objects.all().update(is_confirmed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0019_order_is_confirmed'),
    ]

    operations = [
        migrations.RunPython(set_is_confirmed),
    ]
